{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3-final"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3",
   "language": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Authentication OK\n"
     ]
    }
   ],
   "source": [
    "import tweepy as tw\n",
    "\n",
    "consumer_key= 'yQ4xnp7UG64FkmSc88zQRB4Kk'\n",
    "consumer_secret= 'fSxHYYL3PjiNhAsn0IhLgQNogC5N2qOWBtGokDAlEWrJFi6CuZ'\n",
    "access_token= '1139599692684300288-CjLtSZxQVYoWa86PQlpHvYBuHs1hqn'\n",
    "access_token_secret= 'eqA6quZ27JEMOaFeDOCfVjqzSQjpR9RvOWV6QRvP8GuZR'\n",
    "\n",
    "auth = tw.OAuthHandler(consumer_key, consumer_secret)\n",
    "auth.set_access_token(access_token, access_token_secret)\n",
    "api = tw.API(auth, wait_on_rate_limit=True)\n",
    "\n",
    "try:\n",
    "    api.verify_credentials()\n",
    "    print(\"Authentication OK\")\n",
    "except:\n",
    "    print(\"Error during authentication\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "<tweepy.api.API at 0x1a7848613d0>"
      ]
     },
     "metadata": {},
     "execution_count": 1
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "tags": [
     "outputPrepend"
    ]
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542807811547139\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542809615073286\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542809698955267\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542812572057606\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542818045652993\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542818116919297\n",
      "INFO:root:Processing tweet id 1351542825368907776\n",
      "INFO:root:Processing tweet id 1351542835279966209\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542839809888257\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542849435807746\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542854322159620\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542864128450562\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542868360515584\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542882730184706\n",
      "INFO:root:Processing tweet id 1351542887977263106\n",
      "INFO:root:Processing tweet id 1351542890405777410\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542894411309062\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n",
      "INFO:root:Processing tweet id 1351542899880701955\n",
      "ERROR:root:Error on fav\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 48, in on_status\n",
      "    tweet.favorite()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 131, in favorite\n",
      "    return self._api.create_favorite(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: Twitter error response: status code = 429\n",
      "ERROR:root:Error on fav and retweet\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-4-c4d251994a9b>\", line 54, in on_status\n",
      "    tweet.retweet()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\models.py\", line 125, in retweet\n",
      "    return self._api.retweet(self.id)\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 253, in _call\n",
      "    return method.execute()\n",
      "  File \"C:\\Users\\Alberto\\anaconda3\\lib\\site-packages\\tweepy\\binder.py\", line 234, in execute\n",
      "    raise TweepError(error_msg, resp, api_code=api_error_code)\n",
      "tweepy.error.TweepError: [{'code': 185, 'message': 'User is over daily status update limit.'}]\n"
     ]
    }
   ],
   "source": [
    "# tweepy-bots/bots/config.py\n",
    "import tweepy\n",
    "import logging\n",
    "import os\n",
    "import json\n",
    "\n",
    "logger = logging.getLogger()\n",
    "\n",
    "def create_api():\n",
    "    consumer_key= 'yQ4xnp7UG64FkmSc88zQRB4Kk'\n",
    "    consumer_secret= 'fSxHYYL3PjiNhAsn0IhLgQNogC5N2qOWBtGokDAlEWrJFi6CuZ'\n",
    "    access_token= '1139599692684300288-CjLtSZxQVYoWa86PQlpHvYBuHs1hqn'\n",
    "    access_token_secret= 'eqA6quZ27JEMOaFeDOCfVjqzSQjpR9RvOWV6QRvP8GuZR'\n",
    "\n",
    "    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)\n",
    "    auth.set_access_token(access_token, access_token_secret)\n",
    "    api = tweepy.API(auth, wait_on_rate_limit=True, \n",
    "        wait_on_rate_limit_notify=True)\n",
    "    try:\n",
    "        api.verify_credentials()\n",
    "    except Exception as e:\n",
    "        logger.error(\"Error creating API\", exc_info=True)\n",
    "        raise e\n",
    "    logger.info(\"API created\")\n",
    "    return api\n",
    "\n",
    "create_api()\n",
    "\n",
    "\n",
    "\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "logger = logging.getLogger()\n",
    "\n",
    "class FavRetweetListener(tweepy.StreamListener):\n",
    "    def __init__(self, api):\n",
    "        self.api = api\n",
    "        self.me = api.me()\n",
    "\n",
    "    def on_status(self, tweet):\n",
    "        logger.info(f\"Processing tweet id {tweet.id}\")\n",
    "        if tweet.in_reply_to_status_id is not None or \\\n",
    "            tweet.user.id == self.me.id:\n",
    "            # This tweet is a reply or I'm its author so, ignore it\n",
    "            return\n",
    "        if not tweet.favorited:\n",
    "            # Mark it as Liked, since we have not done it yet\n",
    "            try:\n",
    "                tweet.favorite()\n",
    "            except Exception as e:\n",
    "                logger.error(\"Error on fav\", exc_info=True)\n",
    "        if not tweet.retweeted:\n",
    "            # Retweet, since we have not retweeted it yet\n",
    "            try:\n",
    "                tweet.retweet()\n",
    "            except Exception as e:\n",
    "                logger.error(\"Error on fav and retweet\", exc_info=True)\n",
    "\n",
    "    def on_error(self, status):\n",
    "        logger.error(status)\n",
    "\n",
    "def main(keywords):\n",
    "    \n",
    "    api = create_api()\n",
    "    tweets_listener = FavRetweetListener(api)\n",
    "    stream = tweepy.Stream(api.auth, tweets_listener)\n",
    "    stream.filter(track=keywords, languages=[\"es\"])\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main([\"VOX\"])"
   ]
  }
 ]
}